import tryToGetDeeplTranslation from "./deeplDriver/DeeplDriver";

const demo = await tryToGetDeeplTranslation(
  ["Ceci est un test", "Ceci est un autre test"],
  "en-us",
  { sourceLang: "fr" }
);
console.log(demo);

const demo2 = await tryToGetDeeplTranslation(
  { key1: "Ceci est un test", key2: "Ceci est un autre test" },
  "en-us",
  { sourceLang: "fr" }
);
console.log(demo2);

const demo3 = await tryToGetDeeplTranslation("Ceci est un test", "en-us", {
  sourceLang: "fr",
});
console.log(demo3);

const demo4 = await tryToGetDeeplTranslation(
  ["Ceci est un test", "Ceci est un autre test"],
  "en-us"
);
console.log(demo4);

const demo5 = await tryToGetDeeplTranslation(
  { key1: "Ceci est un test", key2: "Ceci est un autre test" },
  "en-us"
);
console.log(demo5);

const demo6 = await tryToGetDeeplTranslation("Ceci est un test", "en-us");
console.log(demo6);

const demo7 = await tryToGetDeeplTranslation(
  [
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
    "Ceci est un test",
    "Ceci est un autre test",
  ],
  "en-us"
);
console.log(demo7);

const demo8 = await tryToGetDeeplTranslation(
  {
    key1: "Ceci est un test, j'écris un peu n'importe quoi puisqu'il s'agit juste d'une démo. Merci de traduire ce que j'écris même si ça n'a aucun intérêt, c'est pour la science. J'aime les frites et la choucroute. J'aime tous les sports, j'aime aussi faire du vélo. Salut, je m'appelle Alice. Je voudrais me marier avec toi. Les caractères spéciaux c'est trop rigolo, surtout les accents. Bon, et sinon, est-ce que mon driver partitionne correctement mes entrées ?",
    key2: "Ceci est un test, j'écris un peu n'importe quoi puisqu'il s'agit juste d'une démo. Merci de traduire ce que j'écris même si ça n'a aucun intérêt, c'est pour la science. J'aime les frites et la choucroute. J'aime tous les sports, j'aime aussi faire du vélo. Salut, je m'appelle Alice. Je voudrais me marier avec toi. Les caractères spéciaux c'est trop rigolo, surtout les accents. Bon, et sinon, est-ce que mon driver partitionne correctement mes entrées ?",
    key3: "Ceci est un test, j'écris un peu n'importe quoi puisqu'il s'agit juste d'une démo. Merci de traduire ce que j'écris même si ça n'a aucun intérêt, c'est pour la science. J'aime les frites et la choucroute. J'aime tous les sports, j'aime aussi faire du vélo. Salut, je m'appelle Alice. Je voudrais me marier avec toi. Les caractères spéciaux c'est trop rigolo, surtout les accents. Bon, et sinon, est-ce que mon driver partitionne correctement mes entrées ?",
    key4: "Ceci est un autre test",
    key5: "Ceci est un test",
    key6: "Ceci est un test, j'écris un peu n'importe quoi puisqu'il s'agit juste d'une démo. Merci de traduire ce que j'écris même si ça n'a aucun intérêt, c'est pour la science. J'aime les frites et la choucroute. J'aime tous les sports, j'aime aussi faire du vélo. Salut, je m'appelle Alice. Je voudrais me marier avec toi. Les caractères spéciaux c'est trop rigolo, surtout les accents. Bon, et sinon, est-ce que mon driver partitionne correctement mes entrées ?",
    key7: "Ceci est un test",
    key8: "Ceci est un autre test",
    key9: "Kérem, fordítsa le ezt angolra",
    key10: "Por favor, tradúzcalo al inglés",
    key11: "Ceci est un test",
    key12:
      "Ceci est un test, j'écris un peu n'importe quoi puisqu'il s'agit juste d'une démo. Merci de traduire ce que j'écris même si ça n'a aucun intérêt, c'est pour la science. J'aime les frites et la choucroute. J'aime tous les sports, j'aime aussi faire du vélo. Salut, je m'appelle Alice. Je voudrais me marier avec toi. Les caractères spéciaux c'est trop rigolo, surtout les accents. Bon, et sinon, est-ce que mon driver partitionne correctement mes entrées ?",
  },
  "en-us"
);
console.log(demo8);
